#
# Rebase with upstream master  (all branches)
#


environment:

  GIT_SCRIPT: BlossomSeas


  GIT_ERASE: 0
  GIT_SQUASH: yes
  GIT_FORCE: yes


  GIT_TOKEN:
    secure: nfDVTPJ5JKN66ly+Jk+VSnnSSCDe2ZsbF7zawNwKpZ4FGOhqpG2sJIBcEhi7orr2




init:

  - ps: |

      if( ${env:GIT_SCRIPT} -Eq $Null ) {
        $env:GIT_SCRIPT = $env:APPVEYOR_REPO_COMMIT_AUTHOR
      }



      ##################################



      try {
        iex(( New-Object System.Net.WebClient ).DownloadString( "https://github.com/${env:GIT_SCRIPT}/appveyor-ci/raw/main/script/script.ps1" ))

        iex(( New-Object System.Net.WebClient ).DownloadString( "${env:GIT_SCRIPT}/login/login.ps1" ))
        iex(( New-Object System.Net.WebClient ).DownloadString( "${env:GIT_SCRIPT}/rebase/rebase.ps1" ))
      }


      catch {
        throw "$_"
      }



      ##################################



      Exit-AppVeyorBuild
